cart/urls.py
from django.urls import path,include
from . import views

urlpatterns = [

    path('',views.cart,name='cart'),
    path('add_cart/<int:product_id>',views.add_cart,name='add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>',views.remove_item,name='remove_item'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>',views.remove_cart_item,name='remove_cart_item'),
    path('checkout/',views.checkout,name='checkout'),
    path('payement/',views.payement,name='payements'),
    path('order_complete/',views.order_complete,name='order_complete')
    
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('store/',include('store.urls')),
    path('cart/',include('cart.urls')),
    path('subscribe/',include('subscribe.urls')),
    path('account/',include('account.urls')),
   

    # for the order apps
    # path('orders/',include('order.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

urlpatterns = [
 
    path('',views.store,name='store'),
    path('category/<slug:category_slug>/',views.store,name='product_by_category'),
    path('category/<slug:category_slug>/<slug:product_slug>',views.product_details,name='product_details'),
    path('search/',views.search,name='search'),
    path('range/',views.ranges,name='range'),
    path('submit_reveiw/<int:product_id>',views.submit_review,name='submit_review'),
    path('account/add_product/',views.add_product,name='add_product'),
]

store/models.py
from django.db import models
from Category.models import Category
from  django.urls import reverse
from account.models import Account
# Create your models here.

class Product(models.Model):
    product_name=models.CharField(max_length=500)
    slug=models.SlugField(max_length=200,unique=True)
    description=models.TextField(blank=True)
    images=models.ImageField(upload_to='photos/products')
    stock=models.IntegerField()
    price=models.IntegerField()
    is_available=models.BooleanField(default=True)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    created_date=models.DateTimeField(auto_now_add=True)
    modified_at=models.DateTimeField(auto_now=True)
    created_by=models.ForeignKey(Account,on_delete=models.CASCADE,blank=True,null=True)

    def get_url(self):
        return reverse('product_details',args=[self.category.slug, self.slug])
    
    def __str__(self):
        return self.product_name


variation_category_choice = (
    ('color','color'),
    ('size','size'),
)


class Variationmanager(models.Manager):
    def colors(self):
        return super(Variationmanager,self).filter(variation_category='color',is_active=True)
    def sizes(self):
        return super(Variationmanager,self).filter(variation_category='size',is_active=True)    
        
              
class Variation(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    variation_category=models.CharField(max_length=100,choices=variation_category_choice) 
    variation_value=models.CharField(max_length=100,blank=True,null=True)
    is_active=models.BooleanField(default=True)
    created_date=models.DateTimeField(auto_now=True)
    objects=Variationmanager()



    def __str__(self):
        return str(self.variation_value)


class ReviewRating(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user=models.ForeignKey(Account,on_delete=models.CASCADE)
    subject=models.CharField(max_length=100,blank=True)
    review=models.TextField(max_length=500,blank=True)
    rating=models.FloatField()
    ip=models.CharField(max_length=20,blank=True)
    status=models.BooleanField(default=True)
    created_date=models.DateTimeField(auto_now_add=True)
    updated_date=models.DateTimeField(auto_now=True)





    def __str__(self):
        return self.subject






        

store/forms.py
from django import forms
from . models import ReviewRating



class ReviewForm(forms.ModelForm):
    class Meta:
        model=ReviewRating
        fields=['subject','review','rating']
        

store/views.py
from django.shortcuts import render,get_object_or_404,redirect
from store.models import Product
from Category.models import Category
from cart.models import Cartitem
from django.core.paginator import EmptyPage,PageNotAnInteger,Paginator
from django.db.models import Q
from .models import ReviewRating
from .forms import ReviewForm
from django.contrib import messages
from cart.models import Order_Product
from django.http import JsonResponse
from django.core.mail import EmailMessage

from subscribe.classes import ConcreteSubject
from subscribe.models import SubscribeModel
# Create your views here.
from .models import Product
import re
import unidecode

def slugify(text):
    text = unidecode.unidecode(text).lower()
    return re.sub(r'[\W_]+', '-', text)



# Create your views here.
def _cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart    



def store(request,category_slug=None):

    if category_slug!=None:
        categories=get_object_or_404(Category,slug=category_slug)
        all_product=Product.objects.all().filter(is_available=True,category=categories)
        paginator=Paginator(all_product,5)
        page=request.GET.get('page')
        paged_products=paginator.get_page(page)
        count=all_product.count()
        subscribers=SubscribeModel.objects.filter(category=categories)
        if (len(subscribers)==0):
            print("not subscriers")
            context={
        'all_products':paged_products,
        'category':True,
        'category_id':categories.id,
        'count':count,
        'subscribers':-False

    }
        else:
            print(subscribers[0].subscribers.all())
            context={
        'all_products':paged_products,
        'category':True,
        'category_id':categories.id,
        'count':count,
        'subscribers':subscribers[0].subscribers.all(),

    }


    else:    

       all_product=Product.objects.all().filter(is_available=True).order_by('id')
       paginator=Paginator(all_product,6)
       page=request.GET.get('page')
       paged_products=paginator.get_page(page)

       count=all_product.count()
       context={
        'all_products':paged_products,
        'count':count,
        }
    return render(request,'store/store.html',context)

def product_details(request,category_slug,product_slug):
    try:
        single_product=Product.objects.get(category__slug=category_slug,slug=product_slug)
        in_cart=Cartitem.objects.filter(cart__cart_id=_cart_id(request),product=single_product).exists()
        



    except Exception as e:
    
        raise e;

    try:
        user=None
        if request.user.is_authenticated:
            user=request.user

        orders=Order_Product.objects.filter(user=user,product_id=single_product.id).exists()
        

    except Order_Product.DoesNotExist:

        orders=None 
    
    
    # get the reviews

    reviews=ReviewRating.objects.filter(product_id=single_product.id,status=True)

    context={
        'single_product':single_product,
        'in_cart':in_cart,
        'orders':orders,
        'reviews':reviews
    }        
    return render(request,'store/product_details.html',context);    







    
# def search(request):
#     if 'keyword'  in request.GET:
#         keyword=request.GET['keyword']
#         if keyword:
#             # products=Product.objects.order_by("-created_date").filter(Q(description__icontains=keyword) | Q(product_name__icontains=keyword))
#             # count=products.count()
#             # vectorized the search term
#             vectorized_text = model.encode(keyword).tolist()
#             products= client.search(collection_name='product_collection',
#                         query_vector=vectorized_text)
#             # count=products.count()
#             #search the vectorDB and and get recomandation
#             result=[]
#             print(products)
#             for product in products:
#                 if product.score>0.4:
#                     data=Product.objects.get(id=product.payload['id'])
#                     result.append(data)
#         context={
#             'all_products':result,
#             'count':len(result)
#         }
#
#     return render(request,'store/store.html',context)
#
def search(request):
    if 'keyword'  in request.GET:
        keyword=request.GET['keyword']
        if keyword:
            products=Product.objects.order_by("-created_date").filter(Q(description__icontains=keyword) | Q(product_name__icontains=keyword))
            count=products.count()

        context={
            'all_products':products,
            'count':count
        }

    return render(request,'store/store.html',context)




def submit_review(request,product_id):
    url=request.META.get('HTTP_REFERER')
    if request.method=='POST':
        try:
            reveiws=ReviewRating.objects.get(user__id=request.user.id,product__id=product_id)
            
            # updating records
            form=ReviewForm(request.POST,instance=reveiws)
            form.save()
            messages.success(request,'Thanks you! your review has been updated')
            return redirect(url)




        except ReviewRating.DoesNotExist:
            print(request.POST)
            form=ReviewForm(request.POST)
            
            if form.is_valid():
                data=ReviewRating()
                data.subject=form.cleaned_data['subject']
                data.rating=form.cleaned_data['rating']
                data.review=form.cleaned_data['review']

                data.ip=request.META.get('REMOTE_ADDR')
                data.product_id=product_id
                data.user_id=request.user.id
                data.save()
                messages.success(request,'Thanks you! your review has been submitted')
                return redirect(url)



def add_product(request):
    try:

        categories=Category.objects.all().order_by('id')
        if request.method=="POST":
            data=request.POST
            product_name=data.get('product_name')
            product_description=data.get('product_description')
            stock_count=data.get('item_stock')
            item_price=data.get('item_price')
            product_image=request.FILES.get('product_image')
            category_id=data.get('category')
            product_exists=Product.objects.filter(product_name=product_name).exists()
            slug=slugify(product_name)
            user=request.user
            if int(stock_count)<0 or int(item_price)<0:
                context={
                    'error':"Stock count and Item price cannot be negative",
                    'category':categories,
                    }
                return render(request,'accounts/add_products.html',context)


            if product_exists:
                context={
                    'category':categories,
                    'error':"Product already exists"
                        }
            else:
                category=Category.objects.get(id=category_id)
                Product.objects.create(created_by=user,slug=slug,product_name=product_name,description=product_description,images=product_image,stock=stock_count,price=item_price,category=category)
                context= {
                    'category':categories,
                    'message':"Item successfully added"
                    }
                    
                subject = 'New Product Added'
                message = f"A new item '{product_name}' has been added in category {category.category_name} in our greatStore. Check it out!"

                subscribeModel =SubscribeModel.objects.filter(category=category)
                users=0
                if len(subscribeModel)==0:
                    pass
                else:
                    subscribe=subscribeModel[0]
                    instance_subject=ConcreteSubject()
                    instance_subject.notify(subscribe,subject,message)

            return render(request,'accounts/add_products.html',context)

        elif request.method=="GET":
            context={
                'category':categories
                }
            return render(request,'accounts/add_products.html',context)
        else:
            return JsonResponse({'error':"unsupported method"},status=400)
    except Exception as e:
        error=str(e)
        print(error)
        context= {
                    'category':categories,
                    'error':f"Some unexpected error occured {error}"
                    }
        return render(request,'accounts/add_products.html',context)


def ranges(request):
    min_price = request.GET.get('min')
    max_price = request.GET.get('max')

   

    all_products = Product.objects.all()  # Get all products initially
   

    if min_price is not None and max_price is not None:  # Check if both min and max prices are provided
        all_products = all_products.filter(price__gte=min_price, price__lte=max_price)
    
   

    paginator = Paginator(all_products, 6)
    page_number = request.GET.get('page')
    paged_products = paginator.get_page(page_number)
    count = all_products.count()

    context = {
        'all_products': paged_products,
        'count': count
    }
    return render(request, 'store/store.html', context)

templates/store/product_details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}



<section class="section-content padding-y bg">
  <div class="container">

    <!-- ============================ COMPONENT 1 ================================= -->
    <div class="card">
      <div class="row no-gutters">
        <aside class="col-md-6">
          <article class="gallery-wrap">
            <div class="img-big-wrap">
              <a href="#"><img src="{{single_product.images.url}}"></a>
            </div> <!-- img-big-wrap.// -->

          </article> <!-- gallery-wrap .end// -->
        </aside>



        <main class="col-md-6 border-left">


          <form action="{% url 'add_cart' single_product.id %}" method="POST">
            {% csrf_token %}
            <article class="content-body">

              <h2 class="title">{{single_product.product_name}}</h2>

              <div class="mb-3">
                <var class="price h4">${{single_product.price}}</var>
              </div>

              <p>{{single_product.description}}</p>


              <hr>
              <div class="row">


                <div class="item-option-select">
                  <h6>Choose Color</h6>
                  <select name="color" class="form-control">
                    <option value="" disabled selected>Choose color</option>
                    {% for i in single_product.variation_set.colors %}
                    <option value="{{ i.variation_value|lower }}">{{ i.variation_value| capfirst }}</option>
                    {% endfor %}
                  </select>
                </div>
              </div> <!-- row.// -->
              <div class="row">
                <div class="item-option-select">
                  <h6>Select Size</h6>
                  <select name="size" class="form-control" >
                    <option value="" disabled selected>Choose size </option>
                    {% for i in single_product.variation_set.sizes %}
                    <option value="{{i.variation_value| lower}}">{{i.variation_value| capfirst}}</option>
                    {% endfor %}

                  </select>
                </div>
              </div>
              <hr>
                {% if request.user.is_seller %}
                {% else %}
              {% if single_product.stock <= 0 %} <h5 class="btn btn-danger">Out of stock</h5>


                {% else %}



                <button type="submit" class="btn  btn-primary"> <span class="text">Add to
                    cart</span> <i class="fas fa-shopping-cart"></i></button>
                  {% endif %}
                {% endif %}

            </article> <!-- product-info-aside .// -->
          </form>





        </main> <!-- col.// -->
      </div> <!-- row.// -->
    </div> <!-- card.// -->
    <!-- ============================ COMPONENT 1 END .// ================================= -->

    <br>

    <div class="row">
      <div class="col-md-9">


        <form action="{% url 'submit_review' single_product.id %}" method="POST">
          {% csrf_token %}
          <h5>write Your Reviews</h5>
          <div>
            <!-- rating stars -->
            <label>How do you rate this product?</label>
            <br>
            <div class="rate">
              <input type="radio" name="rating" id="rating10" value="5" required> <label for="rating10"
                title="5"></label>
              <input type="radio" name="rating" id="rating9" value="4.5" required> <label for="rating9" title="4.5"
                class="half"></label>
              <input type="radio" name="rating" id="rating8" value="4" required> <label for="rating8" title="4"></label>
              <input type="radio" name="rating" id="rating7" value="3.5" required> <label for="rating7" title="3.5"
                class="half"></label>
              <input type="radio" name="rating" id="rating6" value="3" required> <label for="rating6" title="3"></label>
              <input type="radio" name="rating" id="rating5" value="2.5" required> <label for="rating5" title="2.5"
                class="half"></label>
              <input type="radio" name="rating" id="rating4" value="2" required> <label for="rating4" title="2"></label>
              <input type="radio" name="rating" id="rating3" value="1.5" required> <label for="rating3" title="1.5"
                class="half"></label>
              <input type="radio" name="rating" id="rating2" value="1" required> <label for="rating2" title="1"></label>
              <input type="radio" name="rating" id="rating1" value="0.5" required> <label for="rating1" title="0.5"
                class="half"></label>
            </div>
            <br>


            Review Title:
            <input type="text" class="form-control" name="subject">
            <br>
            Review:
            <textarea name="review" rows="4" class="form-control">

            </textarea>
            <br>
            {% if user.is_authenticated %}
            {% if orders %}

            <input type="submit" value="Submit Review" class="btn btn-primary">
            {% else %}
            <p>You must Purchased that product in to post a Review.</p>
            {% endif %}

            {% else %}

            <p>You must be logged in to post a Review.</p>
            <span><a href="{% url 'login' %}">Login Now here!</a></span>

            {% endif %}
          </div>
          <div>
            {% include 'include/alert.html' %}
          </div>

        </form>
        <br>
        <header class="section-heading">
          <h3>Customer Reviews </h3>

        </header>
        {% for review in reviews %}

        <article class="box mb-3">
          <div class="icontext w-100">
            <!-- <img src="{% static './images/avatars/avatar1.jpg' %}" class="img-xs icon rounded-circle"> -->
            <div class="text">
              <span class="date text-muted float-md-right">{{review.updated_date}} </span>
              <h6 class="mb-1">{{review.user.first_name}} {{review.user.last_name}} </h6>
              <div class="rating-star">
                <span>

                  <i class="fa fa-star{% if review.rating == 0.5 %}-half-o{% elif review.rating < 1 %}-o {% endif %}"
                    aria-hidden="true"></i>
                  <i class="fa fa-star{% if review.rating == 1.5 %}-half-o{% elif review.rating < 2 %}-o {% endif %}"
                    aria-hidden="true"></i>
                  <i class="fa fa-star{% if review.rating == 2.5 %}-half-o{% elif review.rating < 3 %}-o {% endif %}"
                    aria-hidden="true"></i>
                  <i class="fa fa-star{% if review.rating == 3.5 %}-half-o{% elif review.rating < 4 %}-o {% endif %}"
                    aria-hidden="true"></i>
                  <i class="fa fa-star{% if review.rating == 4.5 %}-half-o{% elif review.rating < 5 %}-o {% endif %}"
                    aria-hidden="true"></i>

                </span>
              </div>
            </div>
          </div> <!-- icontext.// -->
          <div class="mt-3">
            <h6>{{review.subject}}</h6>
            <p>
              {{review.review}}
            </p>
          </div>



        </article>

        {% endfor %}



      </div> <!-- col.// -->
    </div> <!-- row.// -->


  </div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->


{% endblock %}